### ISSUE TITLE
Nullpointer in SMP Lookup if record lacks SMP in Oxalis 5.0.0

### ISSUE THREAD

**Issue by OysteinLq** [OxalisCommunity/oxalis#513] opened 2021-05-04 13:44 UTC
Hi, we've tried to upgrade to Oxalis 5.0.0 today, but had to revert on the SMP lookup, because we're experiencing Nullpointers with SMP lookups for a couple of recipients.

It's these particular two:
0192:917537534  
and
9908:943574537

It leads to the pretty unhelpful com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException, which has no stacktrace. We've yet to successfull debug this, but our working theory is that it's related to the fact that in both these cases, we can see in https://my.galaxygw.com/participantlookup  that their SMP is "Unknown". So perhaps there's a NULL there that causes havoc?

If anyone could try to recreate this by looking up something akin to the following:
```
receiver='0192:917537534'
documentType='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1'
processIdentifier='urn:fdc:peppol.eu:2017:poacc:billing:01:1.0'
```

We'd appreciate it, thanks.
In both cases these work just fine on earlier Oxalis.

**Comment by inxkl** [comment] 2021-05-04 19:11
https://github.com/OxalisCommunity/vefa-peppol/issues/41

**Comment by OysteinLq** [comment] 2021-05-05 07:38
Thanks, can confirm that the fix referred to in that issue fixes the problem

**Comment by aaron-kumar** [comment] 2021-05-09 07:06
@OysteinLq : Since both participants "0192:917537534" and "9908:943574537" missing in _SMK (Test environment)_ and also I don't have access to Production AP credentials so I need additional information to understand the problem and then fix it. 

You mentioned "_In both cases these work just fine on earlier Oxalis._". 
Can you let me know the earlier version you are using? Are you using CNAME or NAPTR based lookup in earlier version? 

I am trying to reproduce/fix the issue in Oxalis version 5.0.0 but somehow this issue also need to be fixed in SMP as it may be violating SMP specification (_To be confirmed_). 

P.S. Sorry for delayed response as I was sick for 3 weeks. I am back in Business and will help to fix this possible bug quickly. As a side note, this will be part of upcoming release which will also contains Italy and Finland ICDs code list (eDEC version 7.5)

**Comment by OysteinLq** [comment] 2021-05-10 14:53
Hi, we were (and are) running Oxalis 4.1.2, with AS4 4.1.9, which gives no problems looking up the aforementioned participants.
I don't know about CNAME vs NAPTR, to be honest.

When we used the plain Oxalis 5.0.0, we started getting nullpointers without any informative stacktraces.

Thanks to @inxkl 's comment, we decide to clone 
```
        <artifactId>peppol-lookup</artifactId>
        <groupId>network.oxalis.vefa</groupId>
        <version>2.0.0</version>
```

We then made the single change described in commit  https://github.com/OxalisCommunity/vefa-peppol/commit/84fd271aecbeb5accbfbf9bc1c98639e7f3122e4    
We then ran the plain Oxalis 5.0.0, but with our custom peppol-lookup jarfile inserted in place of the legitimately released one. That seemed to fix our issue, as we no longer had problems looking up or sending to the two participants in question.

Even though that worked fine, we didn't want to keep operating on an unofficial fork of this sort, so **we've reverted to 4.1.2**. for the time being. 

So, in theory, that null check is all that's necessary to fix the issue, unless you see it as symptomatic of a large problem.

I don't have any detailed logs to share, since we've only run this in on a INFO loglevel, and so all the logged details are things from our own system, the most pertinent of which has already been described in the initial post.
But do let me know if we can help in any way, and I'll see what I can do. I'm working part time atm because of parent leave, so I can't guarantee immediate response.

**Comment by aaron-kumar** [comment] 2021-05-14 13:25
Oxalis 5.0.1 released (https://github.com/OxalisCommunity/oxalis/releases/tag/v5.0.1)

**Comment by OysteinLq** [comment] 2021-05-14 13:32
@aaron-kumar Thanks, we updated our test and "pilot" setups with this today, and can confirm that the problem described in this issue has been resolved. We will be testing this for a bit, and will most likely try upgrading our production environment again next week.

Once that's been up for a bit, I'll write an update to the discussion thread https://github.com/OxalisCommunity/oxalis/discussions/511

**Closed** 2021-05-14 13:33 UTC
