### ISSUE TITLE
Issue with Document Delivery

### ISSUE THREAD

**Issue by SanjayasH** [OxalisCommunity/oxalis#621] opened 2023-05-11 10:58 UTC
Hello Team,

In our production environment, we are encountering a failure when attempting to send a document to one of our customers.
 
While documents are being successfully delivered to other customers, we are currently observing this failure only with a specific customer. 

We hope that someone from Oxalis Team will help us to sort this out.

```
com.compello.b2b.oxalisout.service.InvalidTransmissionException: Failed to transmit file: 123456743.xml-67890123.xml after 5 attempts
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:106)
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.dispatch(OxalisOutboundMessageDispatcher.java:77)
    at com.compello.b2b.oxalisout.service.FileProcessor.processFile(FileProcessor.java:39)
    at com.compello.b2b.oxalisout.service.FileProcessor.run(FileProcessor.java:89)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
    at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
    at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
    at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
    at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:99)
    ... 8 common frames omitted
Caused by: javax.xml.ws.soap.SOAPFaultException: These policy alternatives can not be satisfied: 
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
    at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
    at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
    ... 14 common frames omitted
Caused by: org.apache.cxf.ws.policy.PolicyException: These policy alternatives can not be satisfied: 
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
    at org.apache.cxf.ws.policy.AssertionInfoMap.checkEffectivePolicy(AssertionInfoMap.java:179)
    at org.apache.cxf.ws.policy.PolicyVerificationInInterceptor.handle(PolicyVerificationInInterceptor.java:102)
    at org.apache.cxf.ws.policy.AbstractPolicyInterceptor.handleMessage(AbstractPolicyInterceptor.java:44)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:829)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1693)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1570)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1371)
    at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
    at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
    at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
    at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:671)
    at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
    at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
    ... 16 common frames omitted
```

We think that it's worth mentioning that it gives a response as "Not Ok!" with HTTP status code 400 when we try to directly invoke the as4 endpoint of this customer through a GET request:

https://ap.xxxxxxxxxx.com/as4

**Comment by RichardVanMaaren** [comment] 2023-05-16 06:52
Hi,

Interesting, it seems from functional perspectieve the customer AP has an issue with it's endpoint configuration maybe with the certificates ? Did you contact them allready to discuss with them ? Usually an AP has a technical contact person.

Regards,

Richard

**Comment by SanjayasH** [comment] 2023-05-17 11:34
Hi @RichardVanMaaren,

Thank you for your prompt response. We had already reached out to the designated technical contact person prior to raising the issue, and he assured us that the AP was operating without any issues.

But we wanted an additional confirmation from a technical perspective regarding the specified error message. We will be reaching out to the technical contact person once again to gather the necessary details.

Regards, 
Sanjaya

**Comment by aaron-kumar** [comment] 2023-05-29 14:31
@SanjayasH : As per our discussion, I am closing this issue by marking this as duplicate of : https://github.com/OxalisCommunity/Oxalis-AS4/issues/208

**Closed by aaron-kumar** 2023-05-29 14:31 UTC
