### ISSUE TITLE
Oxalis sending out Peppol invoice XML issue.

### ISSUE THREAD

**Issue by SurendarG** [OxalisCommunity/oxalis#517] opened 2021-06-01 07:08 UTC
Dear Friends,

Recently we are getting a strange error which we dont know how to resolve. 
when we send the Peppol Invoices to our customers, few of the invoices were failing due blow Oxalis error, the failed invoice Peppol XML structure and fields are correct, not sure whether its XML structure error or data error. 

please some one enlighten us how to resolve this issue. thanks in advance. 

Error log:
20212021-05-10 23:34:52,662 INFO [no.difi.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value 'X:\PEPPOL\Oxalis'.   2021-05-10 23:34:52,662 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: X:\PEPPOL\Oxalis   2021-05-10 23:34:52,662 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: X:\PEPPOL\Oxalis   2021-05-10 23:34:52,662 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: X:\PEPPOL\Oxalis\oxalis.conf   2021-05-10 23:34:52,678 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:    2021-05-10 23:34:52,678 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: X://PEPPOL//IN   2021-05-10 23:34:52,678 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value 'X:\PEPPOL\Oxalis'.   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: X:\PEPPOL\Oxalis   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: X:\PEPPOL\Oxalis   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: X:\PEPPOL\Oxalis\oxalis.conf   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:    2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: X://PEPPOL//IN   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:    2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PATH: peppol-keystore.jks   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => XXXXXXX: XXXXXXX   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: te-b22ed5a9-1aab-48b9-8921-d131e39ca743   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_XXXXXXX: XXXXXXX   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: null   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:    2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: null   2021-05-10 23:34:53,100 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback   2021-05-10 23:34:53,116 INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate subject: xxx   2021-05-10 23:34:53,116 INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate issuer: xxx  2021-05-10 23:34:53,428 INFO [no.difi.vefa.peppol.security.ModeDetector] Detection error (TEST): Validation of subject principal(CN) failed.   2021-05-10 23:34:53,428 INFO [no.difi.vefa.peppol.security.ModeDetector] Detection error (LOCAL): C   2021-05-10 23:34:54,241 INFO [no.difi.vefa.peppol.security.ModeDetector] Detected mode: XXXXXX   2021-05-10 23:34:54,241 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:   2021-05-10 23:34:54,241 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0   2021-05-10 23:34:54,241 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1   2021-05-10 23:34:54,241 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0   2021-05-10 23:34:54,241 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0       2021-05-10 23:34:55,664 INFO [org.springframework.oxm.jaxb.Jaxb2Marshaller] Creating JAXBContext with context path [no.difi.commons.sbdh.jaxb:org.xmlsoap.schemas.soap.envelope:org.w3.soap:org.w3.xmldsig:org.oasis_open.docs.ebxml_bp.ebbp_signals_2:org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704]   2021-05-10 23:34:57,945 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: An undefined error occurred.   java.util.concurrent.ExecutionException: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: An undefined error occurred.   at java.util.concurrent.FutureTask.report(FutureTask.java:122)   at java.util.concurrent.FutureTask.get(FutureTask.java:192)   at eu.sendregning.oxalis.Main.main(Main.java:227)  Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: An undefined error occurred.   at no.difi.oxalis.as4.outbound.TransmissionResponseExtractor.extractData(TransmissionResponseExtractor.java:59)   at no.difi.oxalis.as4.outbound.TransmissionResponseExtractor.extractData(TransmissionResponseExtractor.java:33)   at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:619)   at no.difi.oxalis.as4.outbound.As4WebServiceTemplate.doSendAndReceive(As4WebServiceTemplate.java:21)   at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)   at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:72)   at no.difi.oxalis.as4.outbound.As4MessageSenderFascade.send(As4MessageSenderFascade.java:22)   at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)   at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)   at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)   at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)   at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)   at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)   at java.util.concurrent.FutureTask.run(FutureTask.java:266)   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)   at java.util.concurrent.FutureTask.run(FutureTask.java:266)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)   at java.lang.Thread.run(Thread.java:745)  Total time spent: 3s  Attempted to send 0 files  Failed transmissions: 1

**Comment by dladlk** [comment] 2021-06-01 14:45
The exception happens in no.difi.oxalis.as4.outbound.TransmissionResponseExtractor - which is definitely not 5.0 version of Oxalis (because of package name), and is absent in 4.1.9 - looks like similar class is called TransmissionResponseConverter.

Try to look at https://github.com/OxalisCommunity/Oxalis-AS4/blob/c57f42eb1a3840f169e2c9e56d0ca36d6848fb1f/src/main/java/no/difi/oxalis/as4/outbound/TransmissionResponseConverter.java#L50 - may be you could expand logging and see what is actually transferred in signalMessage by overwriting this class with your implementation, but with proper version of Oxalis AS4...

**Comment by SurendarG** [comment] 2021-06-04 02:30
Hi Aaron Kumar, 

Thanks for your info, our Oxalis version is 4.x.x and I believe Oxalis have backward version compatibility. 
Around 10% invoices are failing due to this issue every month for the same set of customers (Peppol ID), the rest of the customers are receiving successfully.
Invoice XML structure is same for both success and failed ones. 

Looking forward for your valuable suggestions. thanks

**Comment by aaron-kumar** [comment] 2021-08-08 06:26
@SurendarG : Can you reproduce this issue in Test environment (SMK) ? i.e. do you have some endpoints of receiving AP in SMK environment where you are facing similar problem?  If yes can you share?

**Comment by aaron-kumar** [comment] 2021-09-03 14:45
Due to inactivity from issue reporter (@SurendarG ), it is more likely that it was interoperability issue and may have solved. 
This issue is eligible for automatic close on 7th September, 2021 if no reply received.

In case this issue still persist please provide requested information at the earliest. Thanks

**Comment by aaron-kumar** [comment] 2021-09-08 10:40
@SurendarG  : Closing this stale issue due to lack of information. 
Please feel free to reopen this issue if you face similar problem and you have required input to reproduce this...

**Closed by aaron-kumar** 2021-09-08 10:40 UTC
Labels: Under review
